### ISSUE TITLE
Passing data between C# and C++

### ISSUE THREAD

**Issue by Bucha11** [belivvr/mediasoup-client-cpp#3]
Hi, I have some problems with implemenattion this to my project. Can you describe how I should pass listener's pointer from C# when I creating Recv or Send transports? And then how should I convert MediaStreamTrack and pass pointer to it to dll, and get pointer to MediaStreamTrack and convert it to sound? Thank you.

**Comment by Yu-jinSHIN** [comment]
Oh, Sorry. This project is a work in progress and we are also experiencing several issues and problems. We will review it for public release when development is complete. I'm sorry I couldn't help you.
